### ISSUE TITLE
JSONDetails contains wrong data type for a layout field

### ISSUE THREAD

**Issue by dezrrehm** [zoho/zohocrm-csharp-sdk-6.0#10]
API is returning strings for property "tab_traversal" but JSONDetails.json shows this as an int32
this property is also an int in ZohoCRM\Com\Zoho\Crm\API\Layouts\Sections.cs

Sample of API output for layout meta data
					"display_label": "Account Information",
					"sequence_number": 2,
					"isSubformSection": false,
					**"tab_traversal": "left_to_right",**
					"api_name": "Account Information",
					"column_count": 2,
					"name": "Account Information",
					"generated_type": "default",

**Comment by raja-k-7453** [comment]
Thanks @dezrrehm for notifying us. This has been fixed in this [4.0.0](https://www.nuget.org/packages/ZOHOCRMSDK-6.0/4.0.0) release.
