### ISSUE TITLE
This needs to be converted to dot net standard 

### ISSUE THREAD

**Issue by clmcgrath** [zoho/zohocrm-csharp-sdk-6.0#14]
On your docs page you have dotnet  core cli commands listed ,  but this does not support dotnet core natively when restored it restores 4.6.1 libs which are not fully compatible with .net core ie azure functions , linux etc 

netstandard has been around for 8 years this should be updated to current standards

**Comment by clmcgrath** [comment]
i saw on a pr you closed that you refused , that you didnt want to support standard yet due to old customers still being on net461 
it is possible to support both in the same code base with multiple project files 
you mentioned that you would be supporting standard in your net release what would be the ETA for this 
i have an upcoming project using zoho that i need netcore / net8 support for  i need to make a decision on using your librarys or accessing your api's directly so an ETA would be appreciated

**Comment by raja-k-7453** [comment]
@clmcgrath Thanks for your contribution. We will analyze this, and we will provide it as a separate SDK. This can be considered a requirement. This requirement takes some time to support.

Please reach out to support@zohocrm.com, for more updates. We will follow up on this request, over there.

Thanks!
