### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by germgerm** [zoho/zohocrm-csharp-sdk-6.0#18]
![Screenshot_2024-06-13_06-14-41](https://github.com/zoho/zohocrm-csharp-sdk-6.0/assets/1863991/97a0dff0-f761-4a9e-8ad8-32bb0044e791)

![Screenshot_2024-06-13_06-13-23](https://github.com/zoho/zohocrm-csharp-sdk-6.0/assets/1863991/3e7aba79-634a-4e07-be5d-82439c7982d2)

**Comment by raja-k-7453** [comment]
Thanks, @germgerm for your contribution. This has been updated in the [README.md](https://github.com/zoho/zohocrm-csharp-sdk-6.0/blob/master/ZohoCRM/README.md) file.
