### ISSUE TITLE
Client credential flow

### ISSUE THREAD

**Issue by anatolii-bohdanov** [zoho/zohocrm-csharp-sdk-6.0#25]
How can I use the client credential authentication flow https://www.zoho.com/accounts/protocol/oauth/self-client/client-credentials-flow.html in the current sdk?

**Comment by raja-k-7453** [comment]
@anatolii-bohdanov Please get in touch with [support@zohocrm.com](mailto:support@zohocrm.com). We will follow up on this request, over there.

Thanks!
