### ISSUE TITLE
ITokenStore for local in-memory storage

### ISSUE THREAD

**Issue by anatolii-bohdanov** [zoho/zohocrm-csharp-sdk-6.0#26]
Hey guys

Can you provide an ITokenStore implementation for local in-memory storage (for example MemoryCache or EF Core in-memory DB)?

**Comment by raja-k-7453** [comment]
Thanks, @anatolii-bohdanov  for your contribution. Our C# SDK comes with built-in support for [File Persistence](https://github.com/zoho/zohocrm-csharp-sdk-6.0/blob/master/ZohoCRM/Com/Zoho/API/Authenticator/Store/FileStore.cs), which stores your tokens in a file at a location of your choosing, and [DB Persistence](https://github.com/zoho/zohocrm-csharp-sdk-6.0/blob/master/ZohoCRM/Com/Zoho/API/Authenticator/Store/DBStore.cs), which stores your tokens in a MySQL database. However, if these options don't align with your specific requirements, or if you want to use a database other than MySQL or any other storage method, you can leverage Custom Persistence, where you can define your own storage logic through the ITokenStore interface. To do this, you need to implement the ITokenStore interface and override its methods accordingly.
