### ISSUE TITLE
how to get Quoted_Item's product id's?

### ISSUE THREAD

**Issue by jfferreira97** [zoho/zohocrm-csharp-sdk-6.0#27]
#### Description:
When attempting to fetch product information for quoted items in a **Zoho CRM Quote** using the **C# SDK**, the `FindRelatedRecords` method is unable to access the product details. This occurs despite the fact that this information is readily accessible through **Zoho Deluge** commands.

#### Current Behavior:
- The `FindRelatedRecords` method successfully retrieves quoted items.
- However, the returned quoted items lack any product information.

#### Expected Behavior:
- The method should return quoted items that include associated product details, particularly the product ID.

#### Steps to Reproduce:
1. Use the `FindRelatedRecords` method with `"Quotes"` as the module and `"quoted_items"` as the `fieldName` that calls your function GetRecord
2. Examine the returned `Record` objects.

#### Current Code:

```csharp
public static List<Record> FindRelatedRecords(this string module, string zoho_id, string fieldName, ref string error)
{
    List<Record> records = new List<Record>();
    try
    {
        RecordOperations operations = new RecordOperations(module);
        APIResponse<ResponseHandler> response = operations.GetRecord(long.Parse(zoho_id), null, null);

        if (response?.Object is ResponseWrapper obj && obj.Data != null && obj.Data.Count > 0)
        {
            var record = obj.Data[0];
            var fieldValue = record.GetKeyValue(fieldName);

            if (fieldValue is List<Record> subformRecords)
            {
                // ZohoID is not in the keyvalues in these cases, so it has to be manually added to the ZohoRecords
                records.AddRange(subformRecords.Select(r => { r.AddKeyValue("id", r?.Id ?? 0); return r; }));
            }
            else if (fieldValue is Record lookupRecord)
            {
                records.Add(lookupRecord);
            }
        }
    }
    catch (Exception ex)
    {
        error = $"Module: {module}\nException: {ex}";
    }
    return records;
}
```
#### Questions:
1. Is there a limitation in the C# SDK that prevents accessing product information from quoted items?
2. Are there any additional steps or methods required to retrieve the complete product information?
3. Is there a workaround or alternative approach to obtain the product IDs for quoted items using the C# SDK?
#### Additional Context:
1. The same information is accessible through Zoho Deluge commands, suggesting that the data is available in the CRM but not being properly exposed through the C# SDK.
2. Any insights or solutions to this issue would be greatly appreciated. Thank you for your assistance.

**Comment by raja-k-7453** [comment]
Hi @jfferreiraMD 
Please try the sample code provided below.

```C#
public static List<Record> FindRelatedRecords(this string module, string zoho_id, string fieldName, string error)
{
	List<Record> records = new List<Record>();
	try
	{
		RecordOperations operations = new RecordOperations(module);
		APIResponse<ResponseHandler> response = operations.GetRecord(long.Parse(zoho_id), null, null);
		if (response?.Object is ResponseWrapper obj && obj.Data != null && obj.Data.Count > 0)
		{
			var record = obj.Data[0];
			var fieldValue = record.GetKeyValue(fieldName);
			if (fieldValue is List<Record> subformRecords)
			{
				// ZohoID is not in the keyvalues in these cases, so it has to be manually added to the ZohoRecords
				records.AddRange(subformRecords.Select(r => { r.AddKeyValue("id", r?.Id ?? 0); return r; }));
				foreach (Record quotedItem in subformRecords)
				{
					if (quotedItem.GetKeyValue("Product_Name") != null)
					{
						LineItemProduct product = (LineItemProduct)quotedItem.GetKeyValue("Product_Name");
						Console.WriteLine("Quoted_Items Product Id: " + product.Id);
						Console.WriteLine("Quoted_Items Product Name: " + product.Name);
						Console.WriteLine("Quoted_Items Product ProductCode: " + product.ProductCode);
					}
					foreach (KeyValuePair<string, object> entry1 in quotedItem.GetKeyValues())
					{
						Console.WriteLine(entry1.Key + ": " + entry1.Value);
					}
				}
			}
			else if (fieldValue is Record lookupRecord)
			{
				records.Add(lookupRecord);
			}
		}
	}
	catch (Exception ex)
	{
		error = $"Module: {module}\nException: {ex}";
	}
	return records;
}
```

   Please forward any SDK-related queries to [support@zohocrm.com](mailto:support@zohocrm.com) and we'll take things forward.

**Comment by jfferreira97** [comment]
This did work. Weird how this information isn't accessible on the IEnumerable visualizar but reachable trough code.
Thank you so much!
