### ISSUE TITLE
Unable to Upsert Quotes, always get the error "MANDATORY_NOT_FOUND" "Quoted_Items", even when they're clearly there.

### ISSUE THREAD

**Issue by jfferreira97** [zoho/zohocrm-csharp-sdk-6.0#29]
#### Description:
When attempting to upsert a **Zoho CRM Quote**  after performing minor changes to it's fields, using the **C# SDK**, the `UpsertRawRecords` method is unable to perform this action sucessfuly, the APIException gets thrown  `"MANDATORY_NOT_FOUND" "Quoted_Items"`. This occurs despite the fact that the Quote we are trying to upsert was clearly just fetched, with no fields having been removed, also the **Quoted_Items** key with it's respective values is clearly visible in the **IEnumerable Visualizer**.

#### Current Behavior:
- The `FetchRawRecords` method successfully retrieves a `Quote` with all of it's key values, including `Quoted_Items`.
- However upon trying to upsert them with `UpsertRawRecords`, I get the error:
```json
{"Status":{"Value":"error"},"Code":{"Value":"MANDATORY_NOT_FOUND"},"Message":{"Value":"required field not found"},"Details":{"api_name":"Quoted_Items","json_path":"$.data[0].Quoted_Items"}} 
```
- This happens despite the fact that the `Quote` was just sucessfully retrieved from the C# SDK API, and none of its fields are missing, even with the `Quoted_Items` clearly being there in the **IEnumerable Visualizer**.

#### Expected Behavior:
- The upsert should work without problems as the `Quoted_Items` key value is clearly there.

#### Steps to Reproduce:
1. Use the `FetchRawRecord` method with `"Quotes"` as the `moduleAPIname` and the respective `zoho_id` of the Quote.
2. Verify that clearly, all of the fields are there, including the Key Values for `Quoted_Items`.
![image](https://github.com/user-attachments/assets/e7881b9e-289d-4de4-a70c-2fe5a13e806d)
3. Even though the fields are clearly there, upon running `UpsertRawRecords` with this ZohoRecord as a parameter, i get thrown the aforementioned `APIException`:
![image](https://github.com/user-attachments/assets/940a184e-6764-4616-819e-7f462e791295)

#### Current Code:

```csharp
var quoteRawRecord = env.FetchRawRecord("Quotes", detailedQuote.ZohoQuote.id.ToString());
var quoteItems = quoteRawRecord.GetKeyValue("Quoted_Items"); // this clearly contains the Quoted Items from the object wich is to then be upserted trough the API, so it makes no sense that Im getting thrown the exception telling me they're missing
ZohoResponseDTO response = env.UpsertRawRecords("Quotes", quoteRawRecord); //this here fails with the aforementioned error
```

```csharp
public static Record FetchRawRecord(this ZohoEnvironment environment, string moduleAPIName, string zoho_id)
{
    ZohoController.SDKInitialize(environment);
    string error = null;

    try
    {
        RecordOperations operations = new RecordOperations(moduleAPIName);
        HeaderMap header = new HeaderMap();
        ParameterMap param = new ParameterMap();

        APIResponse<ResponseHandler> response = operations.GetRecord(long.Parse(zoho_id), param, header);

        if (response?.Object is ResponseWrapper obj && obj.Data != null && obj.Data.Count > 0)
        {
            return obj.Data[0];
        }
        else if (response?.StatusCode == 400)
        {
            error += $"Erro ao obter registo do módulo '{moduleAPIName}' com ID '{zoho_id}'. Código de estado: {response.StatusCode}";
        }
    }
    catch (Exception ex)
    {
        error = $"Module: {moduleAPIName}\nException: {ex}";
    }

    return null;
}
```

```csharp
public static ZohoResponseDTO UpsertRawRecords(this ZohoEnvironment environment, string moduleAPIName, params Record[] records)
{
    ZohoController.SDKInitialize(environment);
    ZohoResponseDTO dto = new ZohoResponseDTO();

    JsonSerializerSettings options = new JsonSerializerSettings
    {
        NullValueHandling = NullValueHandling.Ignore
    };

    try
    {
        RecordOperations operations = new RecordOperations(moduleAPIName);
        HeaderMap header = new HeaderMap();
        BodyWrapper body = new BodyWrapper
        {
            Data = records.ToList()
        };
        APIResponse<Com.Zoho.Crm.API.Record.ActionHandler> response = operations.UpsertRecords(body, header);
        dto.StatusCode = Convert.ToInt32(response?.StatusCode);
        dto.StatusDescription = response?.StatusDescription;
        
        if (response?.StatusCode != 200 && response?.Object is Com.Zoho.Crm.API.Record.ActionWrapper action)
        {
            foreach (APIException result in action.Data.OfType<APIException>())
            {
                dto.Errors.Add($"Module:{moduleAPIName}\n{JsonConvert.SerializeObject(result, options)}");
            }
        }
    }
    catch (Exception ex)
    {
        dto.Errors.Add($"Error while processing records : {JsonConvert.SerializeObject(records)} from Module: {moduleAPIName}\nException: {ex}");
    }
    return dto;
}
```

Any insights or solutions to this issue would be greatly appreciated. I need a way to programatically upsert quotes trough the C# SDK . Thank you so much for your assistance.

**Comment by raja-k-7453** [comment]
@jfferreiraMD Please draft a mail to [support@zohocrm.com](mailto:support@zohocrm.com). We will follow up on this request over there.
Thanks!

**Comment by jfferreira97** [comment]
bruh
