### ISSUE TITLE
Why does this project have a lot of repeated code

### ISSUE THREAD

**Issue by rjs5327** [zoho/zohocrm-csharp-sdk-6.0#4]
ResponseHandler for example is repeated in alot of the folders and has nothing in it.  

API Exception is nearly identical in most of the folders, interfaces are called out but why not inherit the class instead of repeating the code.   Or just use a master API Exception in the base layer.  

Is this code autogenerated or something.

**Comment by raja-k-7453** [comment]
@rjs5327 Thank you for your contribution. Except for Util and Oauth2 is generated automatically.
